---
title: "paper_simulations"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{paper_simulations}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load_package}
library(fChange)
# library(devtools);load_all()
```

In the code below, we generate all data for the null tables.
```{r generate_null_data}
path <- getwd()
path <- paste0(path,'/paperFiles/Null/')

nTrials <- 1000
lengths <- c(100,500)
dat_res <- 50
burnin <- 1000

################################################
##  KL Data Generation - Null
################################################
###################
## No Dependence
###################

for(l_idx in 1:length(lengths)){
  
  set.seed(12345+l_idx)
  data <- list()
  
  for(i in 1:nTrials){
    cat(paste0(i,', '))
    data[[i]] <- generate_data_fd(
      ns = lengths[l_idx],
      eigsList = list(1/sqrt(1:5)),
      basesList = list(
        fda::create.bspline.basis(nbasis = 5, norder = 4)
      ),
      meansList = c(0),
      distsArray = c("Normal"),
      evals = seq(0, 1, length.out=dat_res),
      kappasArray = c(0),
      silent = T,
      burnin = burnin
    )
  }
  
  saveRDS(data,paste0(path, 'KL/Data/NullCase_len',l_idx,'_data.rds'))
}


###################
## Mild Dependence
###################

for(l_idx in 1:length(lengths)){
  
  set.seed(12345+l_idx)
  data <- list()
  
  for(i in 1:nTrials){
    cat(paste0(i,', '))
    data[[i]] <- generate_data_fd(
      ns = lengths[l_idx],
      eigsList = list(1/sqrt(1:5)),
      basesList = list(
        fda::create.bspline.basis(nbasis = 5, norder = 4)
      ),
      meansList = c(0),
      distsArray = c("Normal"),
      evals = seq(0, 1, length.out=dat_res),
      kappasArray = c(0.5),
      silent = T,
      burnin = burnin
    )
  }
  
  saveRDS(data,paste0(path, 'KL/Data/NullCase_len',l_idx,'_data_mild.rds'))
}


###################
## Strong Dependence
###################

for(l_idx in 1:length(lengths)){
  
  set.seed(12345+l_idx)
  data <- list()
  
  for(i in 1:nTrials){
    cat(paste0(i,', '))
    data[[i]] <- generate_data_fd(
      ns = lengths[l_idx],
      eigsList = list(1/sqrt(1:5)),
      basesList = list(
        fda::create.bspline.basis(nbasis = 5, norder = 4)
      ),
      meansList = c(0),
      distsArray = c("Normal"),
      evals = seq(0, 1, length.out=dat_res),
      kappasArray = c(0.8),
      silent = T,
      burnin = burnin
    )
  }
  
  saveRDS(data,paste0(path, 'KL/Data/NullCase_len',l_idx,'_data_strong.rds'))
}

################################################
##  OU Data Generation - Null
################################################
###################
## No Dependence
###################

for(l_idx in 1:length(lengths)){
  
  set.seed(12345+l_idx)
  data <- list()
  
  for(i in 1:nTrials){
    cat(paste0(i,', '))
    data[[i]] <- generateOU(res=dat_res,N=lengths[l_idx], burnin=burnin, rho=0)
  }
  
  saveRDS(data,paste0(path, 'OU/Data/OUNull_len',l_idx,'_data.rds'))
}

###################
## Mild Dependence
###################

for(l_idx in 1:length(lengths)){
  
  set.seed(12345+l_idx)
  data <- list()
  
  for(i in 1:nTrials){
    cat(paste0(i,', '))
    data[[i]] <- generateOU(res=dat_res,N=lengths[l_idx], burnin=burnin, rho=0.5)
  }
  
  saveRDS(data,paste0(path, 'OU/Data/OUNull_len',l_idx,'_data_mild.rds'))
  
}

###################
## Strong Dependence
###################

for(l_idx in 1:length(lengths)){
  
  set.seed(12345+l_idx)
  data <- list()
  
  for(i in 1:nTrials){
    cat(paste0(i,', '))
    data[[i]] <- generateOU(res=dat_res,N=lengths[l_idx], burnin=burnin, rho=0.8)
  }
  
  saveRDS(data,paste0(path, 'OU/Data/OUNull_len',l_idx,'_data_strong.rds'))
  
}


################################################
##  FAR(1) Data Generation - Null
################################################
###################
## No Dependence
###################

for(l_idx in 1:length(lengths)){
  
  set.seed(12345+l_idx)
  data <- list()
  
  for(i in 1:nTrials){
    cat(paste0(i,', '))
    data[[i]] <- generateFAR1(resolution=dat_res, N=lengths[l_idx],
                              d=0, burnin=burnin)
  }
  
  saveRDS(data,paste0(path,'FAR1/Data/FAR1Null_len',l_idx,'_data.rds'))
}


###################
## Mild Dependence
###################

for(l_idx in 1:length(lengths)){
  
  set.seed(12345+l_idx)
  data <- list()
  
  for(i in 1:nTrials){
    cat(paste0(i,', '))
    data[[i]] <- generateFAR1(resolution=dat_res, N=lengths[l_idx],
                              d=0.5, burnin=burnin)
  }
  
  saveRDS(data,paste0(path,'FAR1/Data/FAR1Null_len',l_idx,'_data_mild.rds'))
}


###################
## Strong Dependence
###################

for(l_idx in 1:length(lengths)){
  
  set.seed(12345+l_idx)
  data <- list()
  
  for(i in 1:nTrials){
    cat(paste0(i,', '))
    data[[i]] <- generateFAR1(resolution=dat_res, N=lengths[l_idx],
                              d=0.8, burnin=burnin)
  }
  
  saveRDS(data,paste0(path,'FAR1/Data/FAR1Null_len',l_idx,'_data_strong.rds'))
}

```

Compute Statistics
```{r compute_null_data}
#path <- getwd()
#path <- paste0(path,'/paperFiles/Null/KL/')
path <- 'C:/Users/jerem/OneDrive/Documents/School/Waterloo/Research/RPackages/fChange-data/paperFiles/Null/KL/'

    data <- readRDS(paste0(path,'Data/',
                           'NullCase_len',l_idx,'_data.rds'))
function(data_path_start, path){
  nTrials <- 1000
  lengths <- c(100,500)
  dat_res <- 50
  
  for(l_idx in 1:length(lengths)){
    cat(paste0('\n',l_idx,': '))
    results <- data.frame(
      'length'=rep(NA, nTrials),
      'simTnh0'=NA, 'simTnh13'=NA, 'simTnhd13'=NA,
      'simMnh0'=NA, 'simMnh13'=NA, 'simMnhd13'=NA,
      'bootTnh0'=NA,'bootTnh13'=NA,'bootTnhd13'=NA,
      'bootMnh0'=NA,'bootMnh13'=NA,'bootMnhd13'=NA,
      'welchTnh0a5'=NA,'welchTnh13a5'=NA,'welchTnhd13a5'=NA,
      'welchTnh0a1'=NA,'welchTnh13a1'=NA,'welchTnhd13a1'=NA)
  
    data <- readRDS(paste0(data_path_start,l_idx,'_data.rds'))
  
    for(i in 1:nTrials){
      cat(paste0(i,', '))
  
      ## Simulation
      #   Tn and Mn
      set.seed(123456*l_idx+i)
      sim0 <- detect_changepoint_final_TnAndMn(
        data[[i]], h=0,space='BM')
      sim13 <- detect_changepoint_final_TnAndMn(
        data[[i]], h=lengths[l_idx]^(1/3),space='BM')
      simd13 <- detect_changepoint_final_TnAndMn(
        data[[i]], h=2*lengths[l_idx]^(1/3),space='BM')
  
      results[i, c('simTnh0','simTnh13','simTnhd13')] <-
        c(sim0$Tn$pval,sim13$Tn$pval,simd13$Tn$pval)
      results[i, c('simMnh0','simMnh13','simMnhd13')] <-
        c(sim0$Mn$pval,sim13$Mn$pval,simd13$Mn$pval)
      
      ## Bootstrap
      #   Tn
      set.seed(123456*l_idx+i)
      boot0 <- detect_changepoint_bootstrap(
        X=data[[i]], statistic='Tn',
        blockSize=1,space='BM', 
        silent = T)
      boot13 <- detect_changepoint_bootstrap(
        X=data[[i]], statistic='Tn',
        blockSize=lengths[l_idx]^(1/3),space='BM', 
        silent = T)
      bootd13 <- detect_changepoint_bootstrap(
        X=data[[i]], statistic='Tn',
        blockSize=2*lengths[l_idx]^(1/3),space='BM', 
        silent = T)
      
      results[i, c('bootTnh0','bootTnh13','bootTnhd13')] <-
        c(boot0$pval,boot13$pval,bootd13$pval)
      
      #   Mn
      set.seed(123456*l_idx+i)
      boot0 <- detect_changepoint_bootstrap(
        X=data[[i]], statistic='Mn',
        blockSize=1,space='BM', 
        silent = T)
      boot13 <- detect_changepoint_bootstrap(
        X=data[[i]], statistic='Mn',
        blockSize=lengths[l_idx]^(1/3),space='BM', 
        silent = T)
      bootd13 <- detect_changepoint_bootstrap(
        X=data[[i]], statistic='Mn',
        blockSize=2*lengths[l_idx]^(1/3),space='BM', 
        silent = T)
      
      results[i, c('bootMnh0','bootMnh13','bootMnhd13')] <-
        c(boot0$pval,boot13$pval,bootd13$pval)
      
      ## Welch - 0.05
      #   Tn
      set.seed(123456*l_idx+i)
      welch0 <- detect_changepoint_Welch(
        X=data[[i]],
        h=0,space='BM', alpha = 0.05)
      welch13 <- detect_changepoint_Welch(
        X=data[[i]],
        h=lengths[l_idx]^(1/3),space='BM', alpha = 0.05)
      welchd13 <- detect_changepoint_Welch(
        X=data[[i]],
        h=2*lengths[l_idx]^(1/3),space='BM', alpha = 0.05)
      
      results[i, c('welchTnh0a5', 
                   'welchTnh13a5', 
                   'welchTnhd13a5')] <-
        c(tn0$detected, tn13$detected, tnd13$detected)
  
      ## Welch - 0.01
      #   Tn
      set.seed(123456*l_idx+i)
      tn0 <- detect_changepoint_Welch(
        X=data[[i]],
        h=0, space='BM', alpha = 0.01)
      tn13 <- detect_changepoint_Welch(
        X=data[[i]],
        h=lengths[l_idx]^(1/3),space='BM', alpha = 0.01)
      tnd13 <- detect_changepoint_Welch(
        X=data[[i]],
        h=2*lengths[l_idx]^(1/3),space='BM', alpha = 0.01)
  
      results[i, c('welchTnh0a1', 
                   'welchTnh13a1', 
                   'welchTnhd13a1')] <-
        c(tn0$detected, tn13$detected, tnd13$detected)
      
      
      if((nTrials %% 100) == 0)
        saveRDS(results, 
                paste0(path,'tmpResults/', 
                       'Tn_NullCase_len',l_idx,'.rds'))
    }
  
    saveRDS(results, paste0(path,'Results/',
                            'Tn_NullCase_len',l_idx,'.rds'))
  }
  
  results
}
    
################################################
##  KL Data Generation - Null
################################################
###################
## No Dependence
###################
for(l_idx in 1:length(lengths)){
  cat(paste0('\n',l_idx,': '))
  results <- data.frame('length'=rep(NA, nTrials),
                        'tnh0'=NA, 'tnh13'=NA, 'tnhd13'=NA)

  data <- readRDS(paste0(path,'Data/',
                         'NullCase_len',l_idx,'_data.rds'))

  for(i in 1:nTrials){
    cat(paste0(i,', '))

    ## Simulation
    #   Tn and Mn
    set.seed(123456*l_idx+i)
    tn0 <- detect_changepoint_final_TnAndMn(
      data[[i]], h=0,space='BM')
    tn13 <- detect_changepoint_final_TnAndMn(
      data[[i]], h=lengths[l_idx]^(1/3),space='BM')
    tnd13 <- detect_changepoint_final_TnAndMn(
      data[[i]], h=2*lengths[l_idx]^(1/3),space='BM')

    ## Bootstrap
    #   Tn
    set.seed(123456*l_idx+i)
    tn0 <- detect_changepoint_bootstrap(
      X=data[[i]], statistic='Tn',
      blockSize=1,space='BM', silent = T)
    tn13 <- detect_changepoint_bootstrap(
      X=data[[i]], statistic='Tn',
      blockSize=lengths[l_idx]^(1/3),space='BM', silent = T)
    tnd13 <- detect_changepoint_bootstrap(
      X=data[[i]], statistic='Tn',
      blockSize=2*lengths[l_idx]^(1/3),space='BM', silent = T)

    results[i,] <- c(lengths[l_idx],
                     tn0$pval, tn13$pval, tnd13$pval)
    
    #   Mn
    set.seed(123456*l_idx+i)
    mn0 <- detect_changepoint_bootstrap(
      X=data[[i]], statistic='Mn',
      blockSize=1,space='BM', silent = T)
    mn13 <- detect_changepoint_bootstrap(
      X=data[[i]], statistic='Mn',
      blockSize=lengths[l_idx]^(1/3),space='BM', silent = T)
    mnd13 <- detect_changepoint_bootstrap(
      X=data[[i]], statistic='Mn',
      blockSize=2*lengths[l_idx]^(1/3),space='BM', silent = T)

    results[i,] <- c(lengths[l_idx],
                     mn0$pval, mn13$pval, mnd13$pval)
    
    ## Welch - 0.05
    #   Tn
    set.seed(123456*l_idx+i)
    tn0 <- detect_changepoint_Welch(
      X=data[[i]],
      h=0,space='BM', alpha = 0.05)
    tn13 <- detect_changepoint_Welch(
      X=data[[i]],
      h=lengths[l_idx]^(1/3),space='BM', alpha = 0.05)
    tnd13 <- detect_changepoint_Welch(
      X=data[[i]],
      h=2*lengths[l_idx]^(1/3),space='BM', alpha = 0.05)

    results[i,] <- c(lengths[l_idx],
                     tn0$detected, 
                     tn13$detected, 
                     tnd13$detected)

    ## Welch - 0.01
    #   Tn
    set.seed(123456*l_idx+i)
    tn0 <- detect_changepoint_Welch(
      X=data[[i]],
      h=0, space='BM', alpha = 0.01)
    tn13 <- detect_changepoint_Welch(
      X=data[[i]],
      h=lengths[l_idx]^(1/3),space='BM', alpha = 0.01)
    tnd13 <- detect_changepoint_Welch(
      X=data[[i]],
      h=2*lengths[l_idx]^(1/3),space='BM', alpha = 0.01)

    results[i,] <- c(lengths[l_idx],
                     tn0$detected, 
                     tn13$detected, 
                     tnd13$detected)
    
    # results[i,] <- c(lengths[l_idx],
    #                  tn0$pval, tn13$pval, tnd13$pval)

    if((nTrials %% 100) == 0)
      saveRDS(results,paste0(path,'tmpResults/', 'Tn_NullCase_len',l_idx,'.rds'))
  }

  saveRDS(results,paste0(path,'Results/', 'Tn_NullCase_len',l_idx,'.rds'))
}

###################
## Mild Dependence
###################
for(l_idx in 1:length(lengths)){
  cat(paste0('\n',l_idx,': '))
  results <- data.frame('length'=rep(NA, nTrials),
                        'tnh0'=NA, 'tnh13'=NA, 'tnhd13'=NA)

  data <- readRDS(paste0(path,'Data/',
                         'NullCase_len',l_idx,'_data_mild.rds'))

  for(i in 1:nTrials){
    cat(paste0(i,', '))

    set.seed(123456*l_idx+i)
    tn0 <- detect_changepoint_final_Tn(data[[i]], h=0,space='BM')
    tn13 <- detect_changepoint_final_Tn(data[[i]], h=lengths[l_idx]^(1/3),space='BM')
    tnd13 <- detect_changepoint_final_Tn(data[[i]], h=2*lengths[l_idx]^(1/3),space='BM')

    results[i,] <- c(lengths[l_idx],
                     tn0$pval, tn13$pval, tnd13$pval)

    if((nTrials %% 100) == 0)
      saveRDS(results,paste0(path,'tmpResults/', 'Tn_NullCase_len',l_idx,'_mild.rds'))
  }

  saveRDS(results,paste0(path,'Results/', 'Tn_NullCase_len',l_idx,'_mild.rds'))
}


###################
## Strong Dependence
###################
for(l_idx in 1:length(lengths)){
  cat(paste0('\n',l_idx,': '))
  results <- data.frame('length'=rep(NA, nTrials),
                        'tnh0'=NA, 'tnh13'=NA, 'tnhd13'=NA)

  data <- readRDS(paste0(path,'Data/',
                         'NullCase_len',l_idx,'_data_strong.rds'))

  for(i in 1:nTrials){
    cat(paste0(i,', '))

    set.seed(123456*l_idx+i)
    tn0 <- detect_changepoint_final_Tn(data[[i]], h=0,space='BM')
    tn13 <- detect_changepoint_final_Tn(data[[i]], h=lengths[l_idx]^(1/3),space='BM')
    tnd13 <- detect_changepoint_final_Tn(data[[i]], h=2*lengths[l_idx]^(1/3),space='BM')

    results[i,] <- c(lengths[l_idx],
                     tn0$pval, tn13$pval, tnd13$pval)

    if((nTrials %% 100) == 0)
      saveRDS(results,paste0(path,'tmpResults/', 'Tn_NullCase_len',l_idx,'_strong.rds'))
  }

  saveRDS(results,paste0(path,'Results/', 'Tn_NullCase_len',l_idx,'_strong.rds'))
}

```

The mean change figure
```{r mean_change}

```
