// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// cpp_functions.cpp
double dot_integrate(doubles v);
extern "C" SEXP _fChange_dot_integrate(SEXP v) {
  BEGIN_CPP11
    return cpp11::as_sexp(dot_integrate(cpp11::as_cpp<cpp11::decay_t<doubles>>(v)));
  END_CPP11
}
// cpp_functions.cpp
doubles dot_integrate_col(doubles_matrix<> v);
extern "C" SEXP _fChange_dot_integrate_col(SEXP v) {
  BEGIN_CPP11
    return cpp11::as_sexp(dot_integrate_col(cpp11::as_cpp<cpp11::decay_t<doubles_matrix<>>>(v)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_fChange_dot_integrate",     (DL_FUNC) &_fChange_dot_integrate,     1},
    {"_fChange_dot_integrate_col", (DL_FUNC) &_fChange_dot_integrate_col, 1},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_fChange(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
