// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// dot_integrate
double dot_integrate(NumericVector v);
RcppExport SEXP _fChange_dot_integrate(SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(dot_integrate(v));
    return rcpp_result_gen;
END_RCPP
}
// dot_integrate_col
NumericVector dot_integrate_col(NumericMatrix v);
RcppExport SEXP _fChange_dot_integrate_col(SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(dot_integrate_col(v));
    return rcpp_result_gen;
END_RCPP
}
// dot_col_cumsum
ComplexMatrix dot_col_cumsum(ComplexMatrix m);
RcppExport SEXP _fChange_dot_col_cumsum(SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< ComplexMatrix >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(dot_col_cumsum(m));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fChange_dot_integrate", (DL_FUNC) &_fChange_dot_integrate, 1},
    {"_fChange_dot_integrate_col", (DL_FUNC) &_fChange_dot_integrate_col, 1},
    {"_fChange_dot_col_cumsum", (DL_FUNC) &_fChange_dot_col_cumsum, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_fChange(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
