# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dot_integrate <- function(v) {
    .Call(`_fChange_dot_integrate`, v)
}

dot_integrate_col <- function(v) {
    .Call(`_fChange_dot_integrate_col`, v)
}

dot_col_cumsum <- function(m) {
    .Call(`_fChange_dot_col_cumsum`, m)
}

